[config]

[templates.fcitx5]
input_path = '~/.config/matugen/templates/fcitx5-theme.conf'
output_path = '~/.local/share/fcitx5/themes/Matugen/theme.conf'
post_hook= 'fcitx5 -r & disown '

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -SIGUSR1 btop; pkill -SIGUSR2 btop &'

[templates.starship]
input_path = '~/.config/matugen/templates/starship-colors.toml'
output_path = '~/.config/starship.toml'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'
